### PR TITLE
gradle 8 fixes

### LINKED ISSUE #10: Gradle-Upgrade 8.0 fails
gradle-upgrade-8.0 error:
Namespace not specified. Please specify a namespace in the module's build.gradle file like so:

android {
namespace 'com.example.namespace'
}

It would in your project build gradle like that:

android {
    // Conditional for compatibility with AGP <4.2.
    if (project.android.hasProperty("namespace")) {
        namespace 'com.pinciat.external_path'
    }
    compileSdkVersion 33

### PR DESCRIPTION
**Pull request by abdelaziz-mahdy**
fixes: https://github.com/aakashkondhalkar/external_path/issues/10

and removes git ignore files and adds java version

migrated to latest version of kotlin and gradle

### CODE REVIEW

**Comment by abdelaziz-mahdy** [comment]
@aakashkondhalkar if you dont mind merging this let me know, will wait for sometime before releasing external_path_plus to replace this package if i feel like you are not active

**Comment by aakashkondhalkar** [comment]
@abdelaziz-mahdy Thanks for the update! I will review the changes and will get back to you as soon as possible. If you have any specific concerns or need additional feedback, feel free to let me know. I appreciate your patience!

**Comment by abdelaziz-mahdy** [comment]
Thank you, I will wait for the release then, I was thinking of adding integration tests but the android emulator is not stable on ci/cd so I didn't add it

**Comment by aakashkondhalkar** [comment]
This is included and available in version 2.0.0.

**Comment by abdelaziz-mahdy** [comment]
Thank you very much ❤️

**Comment by abdelaziz-mahdy** [comment]
btw i just checked the release in change log you added flutter version requirement but its not true i think, if its required the sdk version needs to be updated too in this line 
https://github.com/aakashkondhalkar/external_path/blob/2d45bdef2bbc293d454e37c5dc624db0a2abec96/pubspec.yaml#L8

**Comment by aakashkondhalkar** [comment]
I Have removed this line.
- REQUIRED: Minimum flutter sdk 3.24.0

Actually the example folder requires Flutter SDK version 3.24.0 or higher to run.

**Comment by abdelaziz-mahdy** [comment]
> I Have removed this line.
> - REQUIRED: Minimum flutter sdk 3.24.0
> 
> Actually the example folder requires Flutter SDK version 3.24.0 or higher to run.

It should not require that, maybe that's because I am running that version it got changed by mistake i will fix it 

Edit: I just checked there is nothing requiring flutter 3.24 do you remember the error you faced ?

**Pull request merged**
